# Generated by Django 2.1.4 on 2018-12-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listings_id',
            new_name='listing_id',
        ),
    ]
