# Generated by Django 2.1.4 on 2018-12-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sity',
            new_name='city',
        ),
    ]
